/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 robo1compressed.glb 
Author: krit yamsaso (กฤษณ์ แย้มสระโส) (https://sketchfab.com/krit_yamsaso)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/battle-robot-warrior-b5e1cc9242844fa391b3840ba79bc8d8
Title: battle robot warrior
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Robo1compressed(props) {
  const { nodes, materials } = useGLTF('/models/robo1compressed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials['tripo_material_5f5557ff-661d-4f08-8a8c-40e0f38ea46f']} />
    </group>
  )
}

useGLTF.preload('/models/robo1compressed.glb')
